#!/bin/bash
# This script bootstraps the project terraform variables from S3 to local directory structure
# Usage: ./env-bootstrap.sh --region us-east-2 --profile aws-example-profile

# Defaults
AWS_REGION="us-east-2"
AWS_PROFILE="default"

# Parse CLI arguments
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --profile) AWS_PROFILE="$2"; shift ;;
    --region) AWS_REGION="$2"; shift ;;
    *) echo "Unknown parameter passed: $1"; exit 1 ;;
  esac
  shift
done

# Detect Terraform workspace as environment name
ENVIRONMENT=$(terraform workspace show 2>/dev/null)

if [[ -z "$ENVIRONMENT" || "$ENVIRONMENT" == "default" ]]; then
  echo "❌ Must have a non-default Terraform workspace selected (e.g., dev, staging, prod)."
  exit 1
fi

echo "🧪 Bootstrapping environment: $ENVIRONMENT in $AWS_REGION..."

# Create necessary directories
mkdir -p ./environment/${ENVIRONMENT}/${AWS_REGION}/
mkdir -p ./global/
mkdir -p ./infra/

# Fetch .tfvars files from S3
aws s3 cp s3://aethernubis-tfvars/env/${ENVIRONMENT}/account.tfvars ./environment/${ENVIRONMENT}/account.tfvars --region "$AWS_REGION" --profile "$AWS_PROFILE"
aws s3 cp s3://aethernubis-tfvars/env/${ENVIRONMENT}/${AWS_REGION}/regional.tfvars ./environment/${ENVIRONMENT}/${AWS_REGION}/regional.tfvars --region "$AWS_REGION" --profile "$AWS_PROFILE"
aws s3 cp s3://aethernubis-tfvars/env/${ENVIRONMENT}/${AWS_REGION}/terraform.auto.tfvars ./environment/${ENVIRONMENT}/${AWS_REGION}/terraform.auto.tfvars --region "$AWS_REGION" --profile "$AWS_PROFILE"
aws s3 cp s3://aethernubis-tfvars/globals/global.tfvars ./global/global.tfvars --region "$AWS_REGION" --profile "$AWS_PROFILE"

echo "✅ tfvars files downloaded to local environment."

# Generate /infra/plan.sh
cat <<EOF > ./infra/plan.sh
#!/bin/bash
# Auto-generated by env-bootstrap.sh

AWS_REGION="$AWS_REGION"
ENVIRONMENT=\$(terraform workspace show)

echo "🚀 Running terraform plan for environment: \$ENVIRONMENT in region: \$AWS_REGION"

terraform plan \\
  -var-file="../environment/\$ENVIRONMENT/account.tfvars" \\
  -var-file="../environment/\$ENVIRONMENT/\$AWS_REGION/regional.tfvars" \\
  -var-file="../global/global.tfvars" \\
  -var-file="../environment/\$ENVIRONMENT/\$AWS_REGION/terraform.auto.tfvars"
EOF

# Generate /infra/apply.sh
cat <<EOF > ./infra/apply.sh
#!/bin/bash
# Auto-generated by env-bootstrap.sh

AWS_REGION="$AWS_REGION"
ENVIRONMENT=\$(terraform workspace show)

echo "🚀 Running terraform apply for environment: \$ENVIRONMENT in region: \$AWS_REGION"

terraform apply \\
  -var-file="../environment/\$ENVIRONMENT/account.tfvars" \\
  -var-file="../environment/\$ENVIRONMENT/\$AWS_REGION/regional.tfvars" \\
  -var-file="../global/global.tfvars" \\
  -var-file="../environment/\$ENVIRONMENT/\$AWS_REGION/terraform.auto.tfvars"
EOF

# Make scripts executable
chmod +x ./infra/plan.sh ./infra/apply.sh

echo "✅ plan.sh and apply.sh created in /infra using current Terraform workspace: $ENVIRONMENT"
